### PR TITLE
Collisions

### PR DESCRIPTION
**Pull request by megsum**

### CODE REVIEW

**Comment by LeahGabrielle** [comment]
the lamps in the shrine room aren't solid?? Everything else looks good.

**Comment by adamjford** [comment]
As noted in chat, looks like the walls in the start room are not prevent things from moving through 'em.

**Comment by LeahGabrielle** [comment]
I'm going to try deleting and putting the walls in again. It's odd since it only seems to be the start room.

**Comment by LeahGabrielle** [comment]
It seems to be because all the other rooms are obj_collision_parent and the start room is still just obj_wall.

**Comment by LeahGabrielle** [comment]
to fix:
- [ ] torch object not solid yet
- [ ] change obj_wall in start room to obj_collision_parent

**Comment by megsum** [comment]
Everything should be fixed! ... Hopefully :S

**Pull request merged**
