### PR TITLE
#29: Weapons - Part 1

### PR DESCRIPTION
**Pull request by adamjford**
- Princess now picks up the Straight Sword that's spawned (for testing purposes) in the first room
- When you hit space, it attacks! Currently you cannot move while attacking, but that can change

### CODE REVIEW

**Comment by adamjford** [comment]
Actually, going to clean this up a bit. Don't merge yet!

**Comment by adamjford** [comment]
K, ready for review now.

**Comment by LeahGabrielle** [comment]
You've added a bunch of game maker files. Like backups and such. Was that on purpose? Otherwise it looks sweet. Attacking is great.

**Comment by adamjford** [comment]
Huh, I didn't add anything like backups intentionally. I'll look into it.

**Comment by LeahGabrielle** [comment]
there is dungeon.project_BACKUP_11584,  dungeon.project_BASE_11584, dungeon.project_LOCAL_11584, dungeon.project_REMOTE_11584, in addition to dungeon.project.

**Comment by adamjford** [comment]
Oh! Those are remnants from a merge. Strange that they didn't get cleaned
up. It was probably because I didn't have a merge tool set up before or
something.

**Comment by LeahGabrielle** [comment]
Figured something like that, but wasn't sure. Want me to merge anyway or wait?

**Comment by adamjford** [comment]
Wait, please!

**Comment by adamjford** [comment]
Ready once again!

**Comment by adamjford** [comment]
Here, have some more stuff!

**Comment by adamjford** [comment]
And more stuff!

**Comment by LeahGabrielle** [comment]
I am controlling the ghost instead of the player ??? What did I do?

**Comment by adamjford** [comment]
I actually JUST noticed that too. Don't merge this! Must have broke something in my new commits.

**Pull request merged**
