### PR TITLE
Attempt at getting wall collision to work

### PR DESCRIPTION
**Pull request by adamjford**
Looks like this tutorial for collisions is a bit of pain to integrate with how we randomly generate the dungeon. Haven't quite figured it out yet.

As far as I can tell, our random dungeon generator treats the whole thing as one room, right? What I've got should be iterating through each "tile", initializing an array of whether it's a wall or not, then checking that array when movement tries to occur.

Instead, it appears to be arbitrary where the player can move, and I can't figure out why. Thoughts?

### CODE REVIEW

**Comment by LeahGabrielle** [comment]
I was wondering if maybe wall tiles get  put underneath floor tiles as it generates.  But I couldn't find a reason that would happen.

**Comment by adamjford** [comment]
Yeah, I was thinking that too. Didn't try anything, though. Is there a way to make floor tiles transparent so we can see any extra walls underneath?

**Comment by LeahGabrielle** [comment]
I would think you could just change the sprite to a transparent square or something. That's a good idea. I didn't try that either.

**Comment by adamjford** [comment]
This is pretty far out of date, and we've got a different solution.

**Pull request closed without merging**
