### PR TITLE
Added Sound Effects

### PR DESCRIPTION
**Pull request by sensible-heart**
Finished adding enemy sound effects and computer noises. I think this will be all I have time to add before tomorrow.

### CODE REVIEW

**Comment by adamjford** [comment]
There's a delay in the game music starting when you get to rm_start. Could I possibly change it such that it gets called in the room creation code? Or did you already try that, and that's why it's started with a 30-step alarm on a separate object?

**Comment by sensible-heart** [comment]
Change whatever you need to. :)

**Comment by adamjford** [comment]
Just making sure you didn't already try my proposed change.

**Comment by adamjford** [comment]
My proposed change doesn't work, which is obvious in retrospect. Room creation code is ran only once, so if you enter rm_6 and leave back the way you came, the music doesn't go back to normal because the room was already created.

**Comment by adamjford** [comment]
Figured out a different way to do it. :+1:

**Pull request merged**
